### PR TITLE
Convert BIDS Stats models to v1

### PR DESCRIPTION
**Pull request by adelavega**
- Added a simple conversion script that will be re at run-time if models are not v1
- Pin latest version and FitLins and test
- Added correct group by command

### CODE REVIEW

**Comment by adelavega** [comment]
That was pretty simple it seems @effigies

**Comment by effigies** [comment]
Long run, I think it makes the most sense in pybids. I would say do it here in the short term because setting up a release cascade is always a pain.

**Comment by adelavega** [comment]
Okay. In the future, lets import this into fitlins / pybids. 
 
I'd like to have a more general conversation about simplifying neuroscout-cli to be the lighest layer around fitlins (to help w/ maintenance and exposing all of fitlins options). When that refactor happens we can export this out.

**Comment by effigies** [comment]
I mean, I would go ahead and open PRs into fitlins/pybids whenever it's convenient. I just wouldn't hold NS releases up just to get everything in the right place right away.

**Pull request merged**
